### ISSUE TITLE
Cannot load settings saved with the GUI into Python

### ISSUE THREAD

**Issue by zhafen** [ageller/Firefly#129]
To reproduce, go to [the live example](https://ageller.github.io/Firefly/), click `Save Settings`, and then try loading the data in python via
```#python
settings = firefly.data_reader.Settings()
settings.loadFromJSON( '~/Downloads/preset.json' )
```

A screenshot of the error is attached below.
![image](https://user-images.githubusercontent.com/8739972/182047962-f215d5d9-4503-4610-bb13-f5864c624003.png)

**Comment by agurvich** [comment]
to be clear, the issue here is that I (inadvertently) added a javascript parameter, `zmin`, to `initViewer.js` and `applyUISelection.js` but not `settings.py`. Error messages like these will crop up every time I do something similar and that is not sustainable IMO. Better to have a single spot where these sorts of parameters are defined so that when I add new hooks they automatically propagate where they are needed (and also we'll be less likely to break presets like we used to do in the past).

**Comment by ageller** [comment]
We could have a separate file (maybe a yaml file?) that defines all of these things (`viewerParams`, `GUIParams`, `Settings`, etc.).  Then that could be read into both Python and Javascript, and if we have the right format, we can know which variable needs to be used where.  I haven't thought deeply about this, but it seems that this approach could solve the problem.

**Comment by agurvich** [comment]
I decided to go with a `DefaultSettings.json` and `DefaultParticleSettings.json` to move all settings defaults to a single place.
