### ISSUE TITLE
firefly CLI is not being added to PATH on windows?

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#135]
why?? :(

**Comment by agurvich** [comment]
seems to work if you download from pypi, just building from source on windows doesn't add `firefly` to the PATH (when using git bash/mingw)

**Comment by ageller** [comment]
I *think* with this new merge, this is working.  Though please recreate this on your end to see if you agree.  I did a `pip install -e .`, and the `firefly ` is found in my PATH (on windows).  It is the same file except for the top line (which points to a slightly different location for python -- not sure why that would be different, unless pip is able to change that??, or maybe it is actually from a different previous regular pip installation in my same conda env?  But I think I deleted this env and recreated it recently and haven't had a regular pip install since.)  Anyway, please check on your end.

**Comment by ageller** [comment]
I can confirm that this works on Windows.  I made edits to the `firefly `executable, then ran `pip install -e .`, and the changes propagated.  I'm closing this issue.

**Comment by agurvich** [comment]
thanks!
