### ISSUE TITLE
Minimal example and other are not working

### ISSUE THREAD

**Issue by fdmatoz** [ageller/Firefly#175]
Thanks you for the amazing work. I've followed all of the steps to install the package but in any example I encounter the following:

![image](https://github.com/ageller/Firefly/assets/12948049/c037cac5-461a-489f-a546-e9f6cdbb5cc9)

Any ideas?

Thanks

**Comment by agurvich** [comment]
Oh yikes! That error message looks familiar to me but I’m surprised by how you’re getting it. Typically that message means you’re trying to load data that’s been written to disk but at a location that isn’t a sub-directory of the Firefly source code. for browser security reasons websites can’t access local files on your computer. If you save it in a sub-directory then the data is actually served alongside the Firefly source code. 

But that’s not at all what it looks like you’re doing… it seems here you’re just trying to pass something through Flask. That means something has gone wrong on our end in parsing the data and it’s breaking around the same place as it would in the scenario above, giving you a similar error. @ageller is the one who has looked at that part of the code the most (and the most recently). I might have some time later tonight to do a dive but let’s see what @ageller thinks. Sorry for the trouble, we’ll get you sorted asap!

**Comment by fdmatoz** [comment]
Hi, thanks. I figure that was an issue with the code not with the browser given that is the example that is in the ntbks folder. Let me know if there is a work around. I'd love to start using it as a replacement for my vtk->paraview pipeline.

**Comment by ageller** [comment]
@fdmatoz can you please give me/us a little bit more information about your installation and setup?  For instance, did you do a standard `pip install firefly` ? What OS are you running?  What version of Python are you using?  

Depending on how you installed Firefly, you may need to explicitly define where the data lives on your machine.  I believe I have also run into this error before when setting up Firefly on my various machines.  If I remember correctly, I've solved this as follows:
```
# define a directory path to send to the spawnFireflyServer command
#     the directory should point to the location of the "static" directory in your firefly distribution, 
#     e.g., in our GitHub repo that is "Firefly/src/firefly"
#     if you are running the notebook from Firefly/src/firefly/ntbks  you could define the directory as
directory = os.path.join(os.getcwd(),'..') 

# then pass this to the server
process = spawnFireflyServer(directory = directory)
```

**Comment by fdmatoz** [comment]
@ageller I'm using conda with python 3.8/3.10 (I tried in both environments). The installation setup is from source as in: http://www.firefly-viz.com/docs/installation.html.

**Comment by ageller** [comment]
Thanks @fdmatoz .  So that I'm 100% clear, which installation process did you follow, "Installing the latest stable release" or "Install from source"? (You should not do both.)  The installation method may determine the solution, and will help me to try to reproduce your error on my end.

**Comment by fdmatoz** [comment]
sorry, I should have been clear. I followed :

Install from source[](http://www.firefly-viz.com/docs/installation.html#install-from-source)

git clone https://github.com/ageller/Firefly.git
python setup.py install

**Comment by ageller** [comment]
@fdmatoz I was able to reproduce your error on my end, and I think I've fixed it.  Please pull down the few changes that I just committed, and try again on your end.  I think there were 2 problems:

1. Sometimes websockets doesn't grab a new connection when you refresh the browser page.  So the communication between the backend (flask) and the frontend can get confused.  I added code to the socektParams.js file in main (which I had in another branch under development) that should fix that particular issue.
2. I believe this installation method is going to require you to define the directory where the data is stored, as I wrote above.  I added this to the minimal example notebook.  

With those changes, everything runs on my end as expected.   You may also consider working in an "incognito" browser tab to make sure that you are starting fresh.  (Also note that I am using WSL on Windows; If my fix doesn't work for you, it may be because of an OS difference.)    

If this doesn't work for you, please let me know.  For what it's worth, this is something that I've run into multiple times... @agurvich somehow has never seen this (though he uses a Mac, which shouldn't matter...) It's validating to me in a strange way that others have encountered a similar issue :)  

One thing on my "to do" list is to make the startup easier for new users.  (I have various ideas to streamline things.)  So thank you for your input!

**Comment by fdmatoz** [comment]
I think is working now. I can explore further the app, if I find any other odd behavior I'm gonna let you know. Many thanks
