### ISSUE TITLE
particles that are off are being drawn (just black)

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#3]
We should try reducing their size to 0, maybe that will make it easier. Alternatively, we can just pass the material an empty list-- though you'd have to call `drawScene` which could be slow.

**Comment by agurvich** [comment]
tested that changing particle size to 0 improves performance-- however, when the particle is switched off the particle size is **not updated** so you have to switch the particles on (either before or after changing the size to 0). Regardless, changing the switcheroo to change the particle size to 0 should circumvent this issue and we could keep the text box the same (returning to that particle size when the switcheroo is returned to the on state)

**Comment by ageller** [comment]
I added a radiusScale attribute for the particles, and now they are set to zero when turned off.  Note simply setting the radii to zero does not make the particles disappear because there is some minimum size for the particles. So the alpha is still necessary.  Hopefully this still provides the desired speed up.
