### ISSUE TITLE
viewerParams.filterLims are not updated after text entry in [flaskGUI]

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#33]
`viewerParams.filterLims` are not updated after text entry in [flaskGUI]-- I added todo comments in gui/slider.js where I think we need to figure out when the text entry pertains to filterLims and then sendToViewer the updated limits

**Comment by ageller** [comment]
multiple problems combined to make this not work. In general I was sending too many simultaneous commands, and I think there was some memory issue with that.  In short, I was updating the camera even when keys were pressed in the GUI, and therefore too many simultaneous commands were being sent, and I was updating the filter values too many times in quick succession because I included that within the on("update"...) bit, which resulted in 4 calls to update for each filter text entry.  I moved the bits that update the viewer from the slider so that we have an on("slide") for the slider itself, and then a separate call in setSliderHandle for any change to the text.  

It should be fixed now.
