### ISSUE TITLE
calling drawScene makes it hard to move filter handle bar

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#4]
perhaps we can only call `drawScene` when the user has finalized their choice (and reduce the particle size to 0 or color them black in the interim, for intractability)

**Comment by agurvich** [comment]
probably tenable to just reduce particle size to 0 when filtering and never reshape the arrays/remake the material. Basically just having an extra array of booleans that you multiply their radii by (1 for show, 0 for don't show -> radius is unchanged for show, radius is 0 for don't show).

**Comment by ageller** [comment]
I added a radiusScale attribute for each particle, and now I am setting both to zero when filtering.  We no longer redraw when filtering.  As noted in the other related issue about on/off, both the radii and alpha are required because there is some minimum particle size that I don't know how to circumvent.  Hopefully this will provide the desired speed up.
