### ISSUE TITLE
when running in flask UI does not correctly start 'hidden'

### ISSUE THREAD

**Issue by agurvich** [ageller/Firefly#89]
Apparently the width of the UI div takes a finite amount of time to calculate or something, I think maybe it's being caught in the middle of an animation because the width isn't exactly the same in the `DOMRect` log statement. The 294 is the same though (which is the `offsetWidth` of the div). 

@ageller , any idea what's going on here? I've spent ~1 hour fiddling with this and am totally stumped. 

<img width="1432" alt="Screen Shot 2022-04-12 at 10 39 13 PM" src="https://user-images.githubusercontent.com/7799423/163095495-5a31ca8f-5623-40a0-b045-126a1e1a5e72.png">
<img width="1437" alt="Screen Shot 2022-04-12 at 10 39 23 PM" src="https://user-images.githubusercontent.com/7799423/163095498-485cbdfc-22e8-4b60-9e9b-74a7516d8f22.png">
<img width="1440" alt="Screen Shot 2022-04-12 at 10 39 31 PM" src="https://user-images.githubusercontent.com/7799423/163095501-7578ba9d-c22e-4b85-8814-adc1c6b6d419.png">

**Comment by ageller** [comment]
Maybe.  If I remember correctly, I did have to build in a setTimeout before shrinking down the GUI initially because it was a few pixels off.  This was because it hadn't finished building the UI before shrinking it, and it relies on the UI size to get the shrinking correct.  Probably the cleanest way would be to have a loop that checks for the GUI to finish being constructed before we shrink it -- actually I think we have a loop for GUIready (or something) that we send to the viewer?  Maybe this initial shrinking could be fired once GUI is ready?

**Comment by agurvich** [comment]
05f64eb3bb66ca5c7313e710ea3e9df5e3d97910

i ended up checking if the gui was ready by checking that the width of the UI had converged
